In [3]:
#import numpy package under np
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sas/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sas/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sas/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sas/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sas/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sas/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sas/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sas/anaconda3\\Library\\include']


In [7]:
x=np.zeros(10)
print(x)


y=np.array([0,0,0,0,0,0,0,0,0,0])
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [8]:
a = np.array([5,7,9,0])
print("%d bytes" % (a.size * a.itemsize))

16 bytes


In [9]:
# How to get the documentation of the numpy add function from the command line
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
#Create a null vector of size 10 but the fifth value which is 1
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#Create a vector with values ranging from 10 to 49
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#Reverse a vector (first element becomes last)
x=np.arange(10,50)
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [23]:
#Create a 3x3 matrix with values ranging from 0 to 8
x=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
x=np.array([1,2,0,0,4,0])
y=len(x)
print(y)
i=0
for i in range(y):
    if x[i]!=0:
        print(i)

6
0
1
4


In [45]:
#Create a 3x3 identity matrix
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
#Create a 3x3x3 array with random values
x = np.random.random((3,3,3))
print(x)

[[[0.82504757 0.20524893 0.68461933]
  [0.3314825  0.91686932 0.82065897]
  [0.85449086 0.29968759 0.9999967 ]]

 [[0.62510048 0.01487552 0.19118884]
  [0.24166346 0.87553207 0.19007425]
  [0.95355095 0.36629292 0.20345637]]

 [[0.91887898 0.13224453 0.47826289]
  [0.61201274 0.02534016 0.3383533 ]
  [0.91894181 0.4772052  0.18944681]]]


In [48]:
#Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10))
print(x) 
min, max = x.min(), x.max()

print(min, max)

[[0.694075   0.61230833 0.41304351 0.456092   0.52102981 0.99359195
  0.86638333 0.56512091 0.73505994 0.69268094]
 [0.38070735 0.34491595 0.5324339  0.14784461 0.42514183 0.95598608
  0.10452468 0.99407553 0.11666975 0.90774933]
 [0.31057357 0.28070643 0.72837399 0.78093175 0.57722651 0.50843056
  0.34565857 0.07789664 0.26006734 0.26862319]
 [0.82411157 0.67923684 0.08524117 0.65279062 0.48066806 0.35234677
  0.9781901  0.10252633 0.21926701 0.1312823 ]
 [0.49608954 0.4389065  0.29565008 0.04726431 0.00414831 0.02429364
  0.30338402 0.09041569 0.27678591 0.95862769]
 [0.4814413  0.81949657 0.97617708 0.30454133 0.05398163 0.43554948
  0.74949364 0.39209671 0.72299593 0.88436283]
 [0.63344538 0.45475559 0.5424699  0.57957923 0.33675958 0.72137122
  0.03272317 0.84820702 0.1269089  0.41086279]
 [0.84329759 0.24761792 0.76913102 0.50680631 0.51951062 0.49410011
  0.64786752 0.50745463 0.84783241 0.21853396]
 [0.20419312 0.32572561 0.78549758 0.26240277 0.6423344  0.44593277
  0.46017363

In [54]:
#Create a random vector of size 30 and find the mean value
from numpy import random

x = np.random.randint(30,size=(30))
print(x)
print(np.mean(x))

[28  1  6  6 11  0  2  3 27 28  6 18 24  3  4  0  3 23 26  3  0 20 21  5
  6 25  5  1 28  2]
11.166666666666666


In [55]:
# Create a 2d array with 1 on the border and 0 inside
x = np.ones((4,4))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [56]:
#How to add a border (filled with 0's) around an existing array?
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
#What is the result of the following expression? (
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [60]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x= np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [61]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
x = np.ones((8,8))

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [62]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [63]:
#Create a checkerboard 8x8 matrix using the tile function
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
#Normalize a 5x5 random matrix 
x= np.random.random((5,5))

print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print(x)

[[0.30474064 0.0091775  0.07408342 0.31671908 0.93743962]
 [0.84744018 0.29455005 0.53320648 0.8525521  0.40919835]
 [0.97968524 0.17980485 0.8799206  0.92059294 0.78097645]
 [0.59902223 0.17814066 0.26484249 0.68811739 0.90364011]
 [0.47652506 0.66921852 0.56445603 0.74160356 0.10947039]]
[[0.30454486 0.         0.06687831 0.31688731 0.9564706 ]
 [0.86373621 0.29404459 0.53995343 0.86900348 0.41217689]
 [1.         0.17581246 0.89720366 0.93911198 0.79525276]
 [0.60776922 0.1740977  0.26343426 0.69957185 0.92164398]
 [0.48154955 0.68009867 0.5721526  0.75468339 0.10334065]]


In [71]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
olor = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [74]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
x= np.random.random((5,3))
y= np.random.random((3,2))
print(x)
print(y)
res = np.dot(x,y)
print(res)

[[0.87072516 0.25950478 0.32597486]
 [0.46276208 0.27172058 0.72211557]
 [0.45211726 0.04419568 0.15347997]
 [0.24997181 0.90568401 0.108406  ]
 [0.68613354 0.32359644 0.97315929]]
[[0.13602295 0.81342508]
 [0.37583503 0.26416367]
 [0.96950442 0.75562993]]
[[0.53200365 1.02313778]
 [0.86516261 0.99385312]
 [0.22690812 0.49541247]
 [0.47948977 0.52449696]
 [1.15843102 1.37894894]]


In [93]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
x = np.arange(1,11,1)
print(x)
i=3
z=8
for i in range(z):
    if i>3:
        y=np.negative(x[i])
        print(y)

[ 1  2  3  4  5  6  7  8  9 10]
-5
-6
-7
-8


In [85]:
# What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10
10
10


In [65]:
# Consider an integer vector Z, which of these expressions are legal? 
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [66]:
# What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

<ipython-input-66-9d5d58bfc011>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-66-9d5d58bfc011>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-66-9d5d58bfc011>:5: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-66-9d5d58bfc011>:6: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


nan
0
[-2.14748365e+09]


In [100]:
#How to round away from zero a float array ?
x=np.array([1.1, 2.01, 7.07, 8.43])
print(x)
print(np.where(x>0, np.ceil(x), np.floor(x)))

[1.1  2.01 7.07 8.43]
[2. 3. 8. 9.]


In [101]:
#How to find common values between two arrays?
x=np.array([1, 2, 7, 8, 12, 45])
y=np.array([1,3,7,9,10,67])
z=np.intersect1d(x,y)
print(z)

[1 7]


In [ ]:
# 31 How to ignore all numpy warnings (not recommended)?

In [67]:
# 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-67-530e0eb0fe17>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-67-530e0eb0fe17>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [102]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-09-08
Today:  2021-09-09
Tomorrow:  2021-09-10


In [104]:
# 34. How to get all the dates corresponding to the month of July 2016? 
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [105]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [107]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods 
x=np.array([1.1, 2.01, 7.07, 8.43])
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[1. 2. 7. 8.]
[1. 2. 7. 8.]
[1 2 7 8]
[1. 2. 7. 8.]


In [111]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 
x=np.matrix([[0,9,8,7,6],[1,7,9,5,4],[2,78,6,0,8],[3,77,34,9,0],[4,99,54,4,3]])
print(x)

[[ 0  9  8  7  6]
 [ 1  7  9  5  4]
 [ 2 78  6  0  8]
 [ 3 77 34  9  0]
 [ 4 99 54  4  3]]


In [112]:
# 38. Consider a generator function that generates 10 integers and use it to build an array 
def generate():
   for n in range(15):
       yield n
x = np.fromiter(generate(),dtype=float,count=-1)

print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [113]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [115]:
# 40. Create a random vector of size 10 and sort it
x=random.randint(100, size=(10))
print(x)
sort(x)
print(sort(x))

[58 71 72 19 76 26 47 25 89 43]
[19 25 26 43 47 58 71 72 76 89]


In [116]:
# 41. How to sum a small array faster than np.sum?
x=random.randint(100, size=(10))
np.add.reduce(x)

442

In [117]:
# 42. Consider two random array A and B, check if they are equal 
x = np.array([1,2,3,4,5])

y = np.array([1,2,3,4,5])
print(np.array_equal(x,y))

True


In [120]:
# 43. Make an array immutable (read-only)
x = np.array([1,8,7,6,9,4])
print(x)
x[1] = 2
print(x) 
x.flags.writeable = False
x[1] = 5

[1 8 7 6 9 4]
[1 2 7 6 9 4]


ValueError: assignment destination is read-only

In [121]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.41356958 0.63224804 1.04004477 0.83444633 0.44931014 1.08196227
 1.24624508 0.65193686 1.04234885 0.2385118 ]
[0.94972929 1.15493105 0.73057305 0.41387844 1.56916617 0.62531007
 0.72139245 0.70135227 0.91389292 0.67461393]


In [122]:
# 45. Create random vector of size 10 and replace the maximum value by 0
x=random.randint(100, size=(10))
print(x)
max_value = np.max(x)
print(max_value)
y = np.where(x==max_value)
print(y)
x[y] = 0
print(x)

[20 42  6 56 41 87 34 38 45 50]
87
(array([5], dtype=int64),)
[20 42  6 56 41  0 34 38 45 50]


In [123]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [129]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
# 48. Print the minimum and maximum representable value for each numpy scalar type


In [127]:
# 49. How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
x=random.randint(100, size=(10))
print(x)

[67 54 82 62 37 79 33 63 69 48]


In [128]:
# 50. How to find the closest value (to a given scalar) in a vector? 
x = np.arange(100)
print(x)
a = 50.55
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
50.55
51


In [131]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
a = np.array([ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
 
print(a)

[['position' list([('x', <class 'float'>, 1), ('y', <class 'float'>, 1)])]
 ['color'
  list([('r', <class 'float'>, 1), ('g', <class 'float'>, 1), ('b', <class 'float'>, 1)])]]


<ipython-input-131-bfdb803d78cb>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])


In [132]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 
a= np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.55511431 0.43901941 0.43722984 0.94607114 0.00956316
  0.3220752  0.45789447 0.76527407 0.78016946 0.47710202 0.38739001
  0.45675775 0.76185156 0.39455355 0.43294132 0.11044934 0.58671978
  0.99933769 0.97072612 0.61853898 0.39573325 0.80220242 0.93139887
  0.55180568 0.6064901  0.62973775 0.68976146 0.82541119 0.63205027
  0.83464767 0.42445747 0.65298379 0.59201682 0.89280711 0.49960552
  0.57756299 0.37286642 0.66506488 0.2238893  0.91351768 0.44051784
  0.8726241  0.35166192 0.79240533 0.3091359  0.85503385 0.49344829
  0.72043519 0.8670542  0.64176181 0.34659553 0.45383852 0.30395028
  0.84413792 0.97844537 0.62695767 0.55421107 0.88587283 0.45842385
  0.75774923 0.68609435 0.7529363  0.59920441 0.71413677 0.4872426
  0.96990902 0.26444473 0.13370775 0.75389051 0.55673123 0.1972268
  0.76886057 0.35553493 0.21331528 0.31863034 0.50506188 0.44941589
  0.66257605 0.79481709 0.80136177 0.80141501 0.91887557 0.71757557
  0.40844501 0.35471101 0.18748773 1.02436987 0.90

In [133]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
a=np.array([ 0.1,  2.009,  2.54, -4.00,  3.1])
print(a.astype(int))

[ 0  2  2 -4  3]


In [ ]:
#54. How to read the following file? 
#1, 2, 3, 4, 5
#6,  ,  , 7, 8
# ,  , 9,10,11


In [134]:
#55. What is the equivalent of enumerate for numpy arrays?
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
#56. Generate a generic 2D Gaussian-like array

In [136]:
#57. How to randomly place p elements in a 2D array?
x= np.random.randint(5, size=(5,3))

print(x)

[[0 0 2]
 [1 1 1]
 [1 3 0]
 [4 4 3]
 [1 0 4]]


In [139]:
#58. Subtract the mean of each row of a matrix
X = np.random.rand(5, 5)
print(X)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.56588814 0.28254706 0.30378648 0.06914457 0.90023834]
 [0.31742571 0.22329477 0.05523387 0.58600696 0.54481358]
 [0.46242895 0.45692924 0.57188441 0.02286705 0.59776331]
 [0.36282796 0.66099987 0.80992728 0.49002738 0.79511495]
 [0.0068345  0.96537492 0.23046151 0.771141   0.05916023]]
[[ 0.14156722 -0.14177386 -0.12053444 -0.35517635  0.47591742]
 [-0.02792927 -0.12206021 -0.29012111  0.24065199  0.1994586 ]
 [ 0.04005436  0.03455465  0.14950982 -0.39950755  0.17538872]
 [-0.26095153  0.03722038  0.18614779 -0.13375211  0.17133546]
 [-0.39975994  0.55878048 -0.17613292  0.36454657 -0.3474342 ]]


In [145]:
#59. How to sort an array by the nth column?
x=np.random.randint(0,10,(4,4))
print(x[x[:,2].argsort()])

[[9 7 0 2]
 [2 4 0 5]
 [2 8 3 2]
 [6 4 5 3]]


In [152]:
#60. How to tell if a given 2D array has null columns?
x = np.random.randint(0,3,(4,6))
print(x)
print((~x.any(axis=0)).any())

[[2 1 0 2 2 2]
 [1 1 1 1 1 1]
 [1 0 2 0 2 1]
 [1 1 0 2 2 0]]
False


In [157]:
#61. Find the nearest value from a given value in an array
x = np.random.uniform(1, 12, 5)
print(x)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)

[5.67882355 2.4595705  6.69927036 2.97950233 8.1484823 ]
2.97950232719505


In [156]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [ ]:
#63. Create an array class that has a name attribute

In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [159]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [160]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
x = np.random.randint(0,5,(3,4,3,4))
sum = x.sum(axis=(-2,-1))
print(sum)

[[21 30 25 22]
 [16 19 23 25]
 [15 19 20 31]]


In [163]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.array([9,7,6,4,3])
S = np.array([5,7,8,4,3])
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[nan nan nan  3.  4.  9. nan  7.  6.]


<ipython-input-163-54008404f405>:6: RuntimeWarning: invalid value encountered in true_divide
  D_means = D_sums / D_counts


In [166]:
#69. How to get the diagonal of a dot product? 
x = np.random.uniform(0,3,(4,4))
y = np.random.uniform(0,3,(4,4))
print(np.dot(x, y))
np.diag(np.dot(x, y))

[[ 5.89315489  7.9848975  12.11899642  9.40615207]
 [13.85670618 10.86222017 19.85537872 17.43544203]
 [ 7.1553276   6.85098827 13.25920615 10.6932647 ]
 [ 7.37274427  4.82386642  9.03919074  8.38722477]]


array([ 5.89315489, 10.86222017, 13.25920615,  8.38722477])

In [167]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

x = np.array([1,2,3,4,5])
print(x)
p = 3
y = np.zeros(len(x) + (len(x)-1)*(p))
y[::p+1] = x
print(y)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [5]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [7]:
#72. How to swap two rows of an array? 
a = np.array([[4,3, 1],[5 ,7, 0],[9, 9, 3],[8, 2, 4]]) 
print(a)
a[[0, 2]] = a[[2, 0]]
print(a)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [ ]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [8]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[2 3 4 4 6]


In [10]:
#75. How to compute averages using a sliding window over an array?
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n

moving_average(np.arange(20),5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])

In [ ]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [13]:
#77. How to negate a boolean, or to change the sign of a float inplace?
x = np.negative([5.007])
print(x)

a = np.array((True, True, False, True, False))
b = np.invert(a)
print(b)

[-5.007]
[False False  True False  True]


In [ ]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [ ]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [ ]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [ ]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [14]:
#82. Compute a matrix rank
matrix = np.array([[1, 2, 1], [3, 4, 7], [3, 6, 3]])
rank = np.linalg.matrix_rank(matrix)
print(rank)

2


In [15]:
#83. How to find the most frequent value in an array?
x = np.array([3,4,3,5,3,7,7,])

print(np.bincount(x).argmax())

3


In [ ]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [ ]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [ ]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 

In [ ]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [ ]:
#88. How to implement the Game of Life using numpy arrays?

In [34]:
#89. How to get the n largest values of an array 
x = np.arange(10)
print(x)
np.random.shuffle(x)
print(x)
y=np.sort(x)
print(y)
n=3
a=len(x)
print(a)

print(y[a-1])
print(y[a-2])
print(y[a-3])

[0 1 2 3 4 5 6 7 8 9]
[3 8 0 7 5 4 2 1 9 6]
[0 1 2 3 4 5 6 7 8 9]
10
9
8
7


In [35]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
x = np.array([3,4,3,5,3,7,7,])
y=np.array([2,6])
car_pr=res = [(a, b) for a in x for b in y]
print(car_pr)

[(3, 2), (3, 6), (4, 2), (4, 6), (3, 2), (3, 6), (5, 2), (5, 6), (3, 2), (3, 6), (7, 2), (7, 6), (7, 2), (7, 6)]


In [36]:
#91. How to create a record array from a regular array? 
x = np.array([("hello", 5.0, 3),
              ("hi", 31.0, 2)])
y = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(y)

[(b'hello',  5., 3) (b'hi', 31., 2)]


In [43]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods 
x =np.random.randint(10)
print(x)
print(x*x*x)
print(np.power(x,3))

9
729
729


In [45]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

x = np.random.randint(0,5,(8,3))
y = np.random.randint(0,5,(2,2))
print(x)
print(y)
z = (x[..., np.newaxis, np.newaxis] == y)
rows = np.where(z.any((3,1)).all(1))[0]
print(rows)

[[0 0 0]
 [4 4 2]
 [1 3 4]
 [0 4 3]
 [3 0 3]
 [3 1 3]
 [2 2 3]
 [2 3 0]]
[[3 0]
 [4 2]]
[2 3 6 7]


In [ ]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [50]:
#95. Convert a vector of ints into a matrix binary representation


In [51]:
#96. Given a two dimensional array, how to extract unique rows?
x = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
uniqueRows = np.unique(x, axis = 0)
print(uniqueRows)

[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]


In [ ]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [ ]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [ ]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [ ]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)